name: Playwright Tests

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '15 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: lts/* }
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npx playwright test --reporter=html
        env:
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT_TOKEN }}
          publish_branch: gh-pages
          publish_dir: playwright-report

      - name: Send Slack report via webhook
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          REPORT_URL: https://volokhmil.github.io/playwright-tests/
          JOB_STATUS: ${{ job.status }}
          REPO: ${{ github.repository }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            --data "{
              \"attachments\": [
                {
                  \"color\": \"${{ env.JOB_STATUS == 'success' && '#36a64f' || '#ff0000' }}\",
                  \"title\": \"Playwright Tests — ${{ env.JOB_STATUS }}\",
                  \"fields\": [
                    { \"title\": \"Repo\",       \"value\": \"${{ env.REPO }}\",        \"short\": true },
                    { \"title\": \"Commit\",     \"value\": \"${{ github.sha }}\",      \"short\": true },
                    { \"title\": \"Run\",        \"value\": \"<${{ env.RUN_URL }}|view run>\", \"short\": false },
                    { \"title\": \"HTML Report\",\"value\": \"<${{ env.REPORT_URL }}|open report>\", \"short\": false }
                  ]
                }
              ]
            }" \
            $SLACK_WEBHOOK_URL
